name: Publish

on:
  push:
    tags:
      - v[0-9]+.*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: install cargo components
        run: rustup component add clippy

      - name: run tests
        run: .github/scripts/test.sh

      - name: publish crates
        run: |
          cargo login ${{ secrets.crates_io }}
          cargo publish
